adobe/aio-cli-plugin-auth

README.md, src/commands/auth/ctx.js, src/commands/auth/index.js, src/commands/auth/login.js, src/commands/auth/logout.js
Cleaned up docs.
Closes #2 
Close #3
=> fix: cleaned up documentation

package.json
=> jsdoc linting

package.json
=> fix(package): update @adobe/aio-lib-core-ims-oauth to version 1.0.1

package.json, src/commands/auth/ctx.js
Fix API change issues
npm test
=> fix: new ims@1.0.0 changed the context API

src/commands/auth/login.js, src/commands/auth/logout.js, test/commands/auth/logout.test.js
=> `aio logout` does not properly logout the cli context

package.json
=> chore(package): update @adobe/aio-lib-ims-oauth, @adobe/aio-lib-ims to v2.1.0

src/commands/auth/login.js, src/commands/auth/logout.js, src/ims-base-command.js
=> fix: debug logging

package.json, src/commands/auth/login.js, src/ims-base-command.js, test/commands/auth/login.test.js, test/ims-base-command.test.js
=> display current org, project and workspace after login

src/commands/auth/login.js, test/commands/auth/login.test.js
=> fix: don't print console config if flag --bare

README.md
=> fix: readme for OAuth authentication

src/ims-base-command.js, test/ims-base-command.test.js
=> fix: $console renamed to `console` (fixes #42)

package.json
=> remove unused deps

.github/workflows/node.js.yml, .github/workflows/on-push-publish-to-npm.yml, .github/workflows/version-bump-publish.yml, package.json
Fixes #55
npm test
npm run e2e
=> fix: @adobe/aio-lib-ims will require node-12 or greater starting July 14th 2021

package.json
1. nvm use 16
2. rm -rf node_modules
3. rm package-lock.json
4. npm i --package-lock --package-lock-only
5. npm test
=> fix: update @adobe/eslint-config-aio-lib-config and its peer dependencies. fix for node-16

package.json, src/commands/auth/ctx.js, src/commands/auth/index.js, src/commands/auth/login.js, src/commands/auth/logout.js, src/ims-base-command.js, test/commands/auth/index.test.js, test/ims-base-command.test.js
Migration to oclif v2.
https://github.com/adobe/aio-cli/issues/340
=> feat. Oclif v2 migration

.github/workflows/prerelease.yml
Created prerelease.yml
This workflow is added to simplify the work around prerelease publishing to npm and update package.json with an npm pre-release version.
https://jira.corp.adobe.com/browse/ACNA-1599
=> feat: ACNA-1599  create prerelease.yml 

package.json, src/commands/auth/login.js, test/commands/auth/login.test.js
=> fix: do not magically alter APIKEY, just use what you are given

.github/workflows/daily.yml
Add workflow for daily unit-tests run
This closes #70 
#70
=> add daily.yml

.github/workflows/node.js.yml
Codecov bash script has been deprecated, use GH action
=> fix: use GH action for codecov

src/commands/auth/login.js, src/commands/auth/logout.js, test/commands/auth/login.test.js
This closes #74
[ACNA-2052](https://jira.corp.adobe.com/browse/ACNA-2052)
#74
=> The force is always with you

src/commands/auth/login.js
=> pass --force flag into ims-lib

.github/workflows/daily.yml, .github/workflows/node.js.yml, .github/workflows/on-push-publish-to-npm.yml, .github/workflows/prerelease.yml, .github/workflows/version-bump-publish.yml
Implement reusable github workflows
[ACNA-1833](https://jira.corp.adobe.com/browse/ACNA-1833)
- Code Reusability
- Avoiding Redundancy
- This will be tested after PR is merged and deployed.
- This is workflow changes can only be tested post merge.
=> ACNA-1833 | Externalising the github workflows
